import "./globals.css"
import type {Metadata} from "next"
import {Noto_Sans_Myanmar} from "next/font/google"
import Layout from "./components/Layout"

const mmFont = Noto_Sans_Myanmar({weight: "400", subsets: ["myanmar"]})

export const metadata: Metadata = {
    title: "Dream Dictionary",
    description: "Generated by create next app",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={mmFont.className}>
                <Layout>{children}</Layout>
            </body>
        </html>
    )
}
